#!/bin/sh
while getopts "ai" opt; do case $opt in
  a)  python -m pip install poetry;
      python -m poetry install --only main;;
  i)  python -m pip install poetry;
      python -m poetry update --sync;;
  esac; done;
python -m poetry run python -m src.run "$@";
